"""Add user_id to candidates

Revision ID: abac9a9cdcb8
Revises: 
Create Date: 2025-09-07 23:38:00.528655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abac9a9cdcb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add user_id column but allow NULLs for now
    op.add_column('candidates', sa.Column('user_id', sa.Integer(), nullable=True))
    
    # Add foreign key constraint
    op.create_foreign_key(
        'fk_candidates_user_id',  # give it a name
        'candidates', 'users',
        ['user_id'], ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'user_id')
    # ### end Alembic commands ###

